### ISSUE TITLE
Starting with the github code, I get this error message after my first move, e4.

### ISSUE THREAD

**Issue by ChristerNilsson** [billjordanchess/JavaScript-Chess#3]
engine2.js:1515 Uncaught TypeError: Cannot set properties of undefined (setting 'from')
    at MakeMove (engine2.js:1515:22)
    at GetValue (board.html:316:1)
    at tbl.rows.<computed>.cells.<computed>.onclick (board.html:184:46)

This error might be ignored, but should be fixed.

**Comment by billjordanchess** [comment]
Hi Christer,

Ive started a major clean-up of the game. I will let you know why it's
going.

Bill J
